# Isley Live Network operator setup wizard (kit root).
param([string]$KitRoot = $PSScriptRoot)
$ErrorActionPreference = "Stop"

function Read-Required([string]$Prompt, [string]$Default = "") {
    $suffix = if ($Default) { " [$Default]" } else { "" }
    $value = Read-Host "$Prompt$suffix"
    if ([string]::IsNullOrWhiteSpace($value)) { return $Default }
    return $value.Trim()
}
function New-Secret([int]$Bytes = 32) {
    $buffer = New-Object byte[] $Bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($buffer)
    return ([Convert]::ToBase64String($buffer) -replace '[+/=]', 'x')
}

Write-Host "ISLEY LIVE NETWORK · SETUP WIZARD"
$serverId = Read-Required "Server id" "my-isle-server"
$serverName = Read-Required "Public server name" "My Isle Server"
$relayPublicUrl = Read-Required "Public HTTPS relay base URL" "https://relay.example/"
if ($relayPublicUrl -notmatch '^https://' -and $relayPublicUrl -notmatch '^http://(127\.0\.0\.1|localhost)(:|/|$)') {
    throw "Public relay URL must be https:// (loopback http allowed for local tests)."
}
$sourceMode = Read-Required "Source mode: Rcon or Plugin" "Rcon"
if ($sourceMode -notin @("Rcon", "Plugin")) { throw "Source mode must be Rcon or Plugin." }
$bridgeSecret = New-Secret 36
$pluginKey = New-Secret 36
$bridgeDir = Join-Path $KitRoot "Isley.ServerBridge"
$relayDir = Join-Path $KitRoot "Isley.Relay"
if (-not (Test-Path (Join-Path $bridgeDir "Isley.ServerBridge.dll"))) {
    throw "Run from the extracted Isley-Server-Network kit."
}
$stateRoot = Read-Required "Relay state folder" (Join-Path $env:ProgramData "IsleyRelay")
New-Item -ItemType Directory -Force -Path (Join-Path $stateRoot "keys"), (Join-Path $stateRoot "state") | Out-Null
$outDir = Join-Path $KitRoot "operator-local"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null
$lines = @(
    "# Generated by setup.ps1 — keep private.",
    "`$ErrorActionPreference = 'Stop'",
    "`$env:Bridge__ServerId = '$serverId'",
    "`$env:Bridge__ServerName = '$($serverName -replace "'", "''")'",
    "`$env:Bridge__RelayUrl = '$($relayPublicUrl.TrimEnd('/'))/'",
    "`$env:Bridge__RelaySecret = '$bridgeSecret'",
    "`$env:Bridge__SourceMode = '$sourceMode'",
    "`$env:Relay__PublicBaseUrl = '$($relayPublicUrl.TrimEnd('/'))/'",
    "`$env:Relay__DataProtectionKeysPath = '$(Join-Path $stateRoot 'keys')'",
    "`$env:Relay__StatePath = '$(Join-Path $stateRoot 'state')'",
    "`$env:Relay__Bridges__0__ServerId = '$serverId'",
    "`$env:Relay__Bridges__0__Secret = '$bridgeSecret'"
)
if ($sourceMode -eq "Rcon") {
    $rconHost = Read-Required "RCON host" "127.0.0.1"
    $rconPort = Read-Required "RCON port" "8888"
    $secure = Read-Host "RCON password" -AsSecureString
    $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    try { $plain = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr) }
    finally { [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr) }
    if ([string]::IsNullOrWhiteSpace($plain)) { throw "RCON password required." }
    $lines += "`$env:Rcon__Host = '$rconHost'"
    $lines += "`$env:Rcon__Port = '$rconPort'"
    $lines += "`$env:Rcon__Password = '$($plain -replace "'", "''")'"
    $lines += "`$env:Rcon__PollIntervalMilliseconds = '250'"
    Write-Host "RCON mode: facing/sickness/AI stay unavailable until you add a plugin. See RCON_TO_PLUGIN.md"
} else {
    $lines += "`$env:Bridge__PluginEnabled = 'true'"
    $lines += "`$env:Bridge__PluginKey = '$pluginKey'"
}
$envFile = Join-Path $outDir "run-env.ps1"
Set-Content -LiteralPath $envFile -Value $lines -Encoding UTF8
@"
1. . '$envFile'
2. Start Relay, then Bridge
3. Open operator-console.html for loopback status
4. Player join: $($relayPublicUrl.TrimEnd('/'))/join/$serverId
5. If FEED lacks FACING/COND/AI, read RCON_TO_PLUGIN.md
"@ | Set-Content (Join-Path $outDir "OPERATOR_CHECKLIST.txt") -Encoding UTF8
Write-Host "Wrote $envFile"
Write-Host "Join link: $($relayPublicUrl.TrimEnd('/'))/join/$serverId"
