<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>TelemetryPlatformVerifier</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\Isley.Telemetry\Isley.Telemetry.csproj" />
    <ProjectReference Include="..\..\Isley.Relay\Isley.Relay.csproj" />
    <ProjectReference Include="..\..\Isley.ServerBridge\Isley.ServerBridge.csproj" />
    <Compile Include="..\..\BurntHud\IsleyRelayClient.cs" Link="IsleyRelayClient.cs" />
  </ItemGroup>

</Project>
